version: '3.8'

services:
  # Local Persist Volume Plugin
  local-persist:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: local-persist-plugin
    restart: unless-stopped
    privileged: true  # Required for volume plugin operations
    network_mode: host
    volumes:
      # Plugin socket communication with Docker daemon
      - /run/docker/plugins/:/run/docker/plugins/
      # State persistence for plugin data
      - ${PLUGIN_DATA_PATH:-/var/lib/docker/plugin-data}:/var/lib/docker/plugin-data/
      # Docker socket access for container operations
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # Host filesystem access for volume creation
      - /data:/data
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
    healthcheck:
      test: ["CMD", "test", "-S", "/run/docker/plugins/local-persist.sock"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  default:
    name: local-persist-network
    driver: bridge